//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Input/PlayerInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Coconut Controls"",
            ""id"": ""84718ec5-c53f-4d31-adfc-7143de572a31"",
            ""actions"": [
                {
                    ""name"": ""P1 Jump"",
                    ""type"": ""Button"",
                    ""id"": ""229eb316-6ab7-40d5-8c5a-dddd3d914a5a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P1 Ability"",
                    ""type"": ""Button"",
                    ""id"": ""bfa97d47-a82d-4da7-a8c2-ff99538df94f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2 Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8cfb46a8-2d1e-4225-a11b-417a4219c6ab"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P2 Ability"",
                    ""type"": ""Button"",
                    ""id"": ""cf3226dc-1125-4163-98b9-9dacfbfcd427"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P3 Jump"",
                    ""type"": ""Button"",
                    ""id"": ""8acd0b93-8ade-4ad9-9cdc-8a6a8edb2f0e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P3 Ability"",
                    ""type"": ""Button"",
                    ""id"": ""6906d8f6-a991-462a-ac7e-60e136d07614"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P4 Jump"",
                    ""type"": ""Button"",
                    ""id"": ""0d93ddf6-92b0-4b36-b953-ef02a0a89844"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""P4 Ability"",
                    ""type"": ""Button"",
                    ""id"": ""3e66b2a0-33a8-4276-87d5-77dc0214094c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""61096705-3afe-456e-ac67-34bafa236a20"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1 Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04bd449c-720a-48e0-9668-b9b251f11513"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P1 Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb8f42c8-46da-4e25-9ddd-eec758020997"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2 Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6778a6c3-856a-41cb-9984-0ab48f2f48d6"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P2 Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e990b208-d1bc-4056-a434-4f6de197c5d5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P3 Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d5b1cc4-8e29-49ab-a573-7e1c6e82e77f"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P3 Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfe2d579-d25a-4d93-a97a-fc42f897d65e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P4 Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c00179ab-b76c-47c7-95b6-da926900cb89"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""P4 Ability"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Coconut Controls
        m_CoconutControls = asset.FindActionMap("Coconut Controls", throwIfNotFound: true);
        m_CoconutControls_P1Jump = m_CoconutControls.FindAction("P1 Jump", throwIfNotFound: true);
        m_CoconutControls_P1Ability = m_CoconutControls.FindAction("P1 Ability", throwIfNotFound: true);
        m_CoconutControls_P2Jump = m_CoconutControls.FindAction("P2 Jump", throwIfNotFound: true);
        m_CoconutControls_P2Ability = m_CoconutControls.FindAction("P2 Ability", throwIfNotFound: true);
        m_CoconutControls_P3Jump = m_CoconutControls.FindAction("P3 Jump", throwIfNotFound: true);
        m_CoconutControls_P3Ability = m_CoconutControls.FindAction("P3 Ability", throwIfNotFound: true);
        m_CoconutControls_P4Jump = m_CoconutControls.FindAction("P4 Jump", throwIfNotFound: true);
        m_CoconutControls_P4Ability = m_CoconutControls.FindAction("P4 Ability", throwIfNotFound: true);
    }

    ~@PlayerInputs()
    {
        UnityEngine.Debug.Assert(!m_CoconutControls.enabled, "This will cause a leak and performance issues, PlayerInputs.CoconutControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Coconut Controls
    private readonly InputActionMap m_CoconutControls;
    private List<ICoconutControlsActions> m_CoconutControlsActionsCallbackInterfaces = new List<ICoconutControlsActions>();
    private readonly InputAction m_CoconutControls_P1Jump;
    private readonly InputAction m_CoconutControls_P1Ability;
    private readonly InputAction m_CoconutControls_P2Jump;
    private readonly InputAction m_CoconutControls_P2Ability;
    private readonly InputAction m_CoconutControls_P3Jump;
    private readonly InputAction m_CoconutControls_P3Ability;
    private readonly InputAction m_CoconutControls_P4Jump;
    private readonly InputAction m_CoconutControls_P4Ability;
    /// <summary>
    /// Provides access to input actions defined in input action map "Coconut Controls".
    /// </summary>
    public struct CoconutControlsActions
    {
        private @PlayerInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CoconutControlsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P1Jump".
        /// </summary>
        public InputAction @P1Jump => m_Wrapper.m_CoconutControls_P1Jump;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P1Ability".
        /// </summary>
        public InputAction @P1Ability => m_Wrapper.m_CoconutControls_P1Ability;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P2Jump".
        /// </summary>
        public InputAction @P2Jump => m_Wrapper.m_CoconutControls_P2Jump;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P2Ability".
        /// </summary>
        public InputAction @P2Ability => m_Wrapper.m_CoconutControls_P2Ability;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P3Jump".
        /// </summary>
        public InputAction @P3Jump => m_Wrapper.m_CoconutControls_P3Jump;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P3Ability".
        /// </summary>
        public InputAction @P3Ability => m_Wrapper.m_CoconutControls_P3Ability;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P4Jump".
        /// </summary>
        public InputAction @P4Jump => m_Wrapper.m_CoconutControls_P4Jump;
        /// <summary>
        /// Provides access to the underlying input action "CoconutControls/P4Ability".
        /// </summary>
        public InputAction @P4Ability => m_Wrapper.m_CoconutControls_P4Ability;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CoconutControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CoconutControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CoconutControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CoconutControlsActions" />
        public void AddCallbacks(ICoconutControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CoconutControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CoconutControlsActionsCallbackInterfaces.Add(instance);
            @P1Jump.started += instance.OnP1Jump;
            @P1Jump.performed += instance.OnP1Jump;
            @P1Jump.canceled += instance.OnP1Jump;
            @P1Ability.started += instance.OnP1Ability;
            @P1Ability.performed += instance.OnP1Ability;
            @P1Ability.canceled += instance.OnP1Ability;
            @P2Jump.started += instance.OnP2Jump;
            @P2Jump.performed += instance.OnP2Jump;
            @P2Jump.canceled += instance.OnP2Jump;
            @P2Ability.started += instance.OnP2Ability;
            @P2Ability.performed += instance.OnP2Ability;
            @P2Ability.canceled += instance.OnP2Ability;
            @P3Jump.started += instance.OnP3Jump;
            @P3Jump.performed += instance.OnP3Jump;
            @P3Jump.canceled += instance.OnP3Jump;
            @P3Ability.started += instance.OnP3Ability;
            @P3Ability.performed += instance.OnP3Ability;
            @P3Ability.canceled += instance.OnP3Ability;
            @P4Jump.started += instance.OnP4Jump;
            @P4Jump.performed += instance.OnP4Jump;
            @P4Jump.canceled += instance.OnP4Jump;
            @P4Ability.started += instance.OnP4Ability;
            @P4Ability.performed += instance.OnP4Ability;
            @P4Ability.canceled += instance.OnP4Ability;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CoconutControlsActions" />
        private void UnregisterCallbacks(ICoconutControlsActions instance)
        {
            @P1Jump.started -= instance.OnP1Jump;
            @P1Jump.performed -= instance.OnP1Jump;
            @P1Jump.canceled -= instance.OnP1Jump;
            @P1Ability.started -= instance.OnP1Ability;
            @P1Ability.performed -= instance.OnP1Ability;
            @P1Ability.canceled -= instance.OnP1Ability;
            @P2Jump.started -= instance.OnP2Jump;
            @P2Jump.performed -= instance.OnP2Jump;
            @P2Jump.canceled -= instance.OnP2Jump;
            @P2Ability.started -= instance.OnP2Ability;
            @P2Ability.performed -= instance.OnP2Ability;
            @P2Ability.canceled -= instance.OnP2Ability;
            @P3Jump.started -= instance.OnP3Jump;
            @P3Jump.performed -= instance.OnP3Jump;
            @P3Jump.canceled -= instance.OnP3Jump;
            @P3Ability.started -= instance.OnP3Ability;
            @P3Ability.performed -= instance.OnP3Ability;
            @P3Ability.canceled -= instance.OnP3Ability;
            @P4Jump.started -= instance.OnP4Jump;
            @P4Jump.performed -= instance.OnP4Jump;
            @P4Jump.canceled -= instance.OnP4Jump;
            @P4Ability.started -= instance.OnP4Ability;
            @P4Ability.performed -= instance.OnP4Ability;
            @P4Ability.canceled -= instance.OnP4Ability;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CoconutControlsActions.UnregisterCallbacks(ICoconutControlsActions)" />.
        /// </summary>
        /// <seealso cref="CoconutControlsActions.UnregisterCallbacks(ICoconutControlsActions)" />
        public void RemoveCallbacks(ICoconutControlsActions instance)
        {
            if (m_Wrapper.m_CoconutControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CoconutControlsActions.AddCallbacks(ICoconutControlsActions)" />
        /// <seealso cref="CoconutControlsActions.RemoveCallbacks(ICoconutControlsActions)" />
        /// <seealso cref="CoconutControlsActions.UnregisterCallbacks(ICoconutControlsActions)" />
        public void SetCallbacks(ICoconutControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CoconutControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CoconutControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CoconutControlsActions" /> instance referencing this action map.
    /// </summary>
    public CoconutControlsActions @CoconutControls => new CoconutControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Coconut Controls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CoconutControlsActions.AddCallbacks(ICoconutControlsActions)" />
    /// <seealso cref="CoconutControlsActions.RemoveCallbacks(ICoconutControlsActions)" />
    public interface ICoconutControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "P1 Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Jump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P1 Ability" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP1Ability(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2 Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Jump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P2 Ability" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP2Ability(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P3 Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP3Jump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P3 Ability" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP3Ability(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P4 Jump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP4Jump(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "P4 Ability" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnP4Ability(InputAction.CallbackContext context);
    }
}
